#ifndef SCREENBUFFER_H
#define SCREENBUFFER_H

#include <default_types.h>
#include <string>
#include <vector>

/**
 * Off-screen representation of the contents of the terminal
 *
 * Terminal output that is generated by the display classes is not sent to the terminal directly.
 * It is interpreted by the apply() method and painted into the back buffer instead.
 * The render() method then compares the back buffer to the front buffer, which holds the contents that
 * the terminal is currently displaying, and generates the sequence that updates only those parts of
 * the terminal that actually changed.
 *
 * This avoids clearing and repainting the entire screen for every display update, which is what makes
 * the display flicker.
 *
 * The subset of control sequences that is interpreted covers the sequences that the display classes
 * generate: cursor positioning, SGR (colors and text attributes), erase in line, erase in display and
 * the cursor visibility sequences. Sequences that are not interpreted are ignored, therefore the
 * sequences that set up or reset the terminal must be written while the screen buffer is disabled.
 */
class ScreenBuffer
{
  public:
    static constexpr uint16_t MIN_DIMENSION     = 1;
    static constexpr uint16_t MAX_DIMENSION     = 1000;

    // Number of unchanged cells that are rewritten rather than skipped by a cursor positioning sequence
    static constexpr uint16_t MAX_SKIP_LENGTH   = 6;

    // @throws std::bad_alloc
    ScreenBuffer(const uint16_t init_cols, const uint16_t init_rows);
    virtual ~ScreenBuffer() noexcept;
    ScreenBuffer(const ScreenBuffer& other)                     = delete;
    ScreenBuffer(ScreenBuffer&& other)                          = delete;
    virtual ScreenBuffer& operator=(const ScreenBuffer& other)  = delete;
    virtual ScreenBuffer& operator=(ScreenBuffer&& orig)        = delete;

    /**
     * Adjusts the dimensions of the buffers
     *
     * The contents of the buffers are discarded and the next render() call updates the entire terminal.
     *
     * @throws std::bad_alloc
     */
    virtual void set_dimensions(const uint16_t new_cols, const uint16_t new_rows);

    /**
     * Discards the assumption about what the terminal is currently displaying
     *
     * The next render() call updates the entire terminal. To be called whenever the contents of the
     * terminal may have been changed by anything other than this class.
     */
    virtual void invalidate() noexcept;

    /**
     * Interprets terminal output and applies it to the back buffer
     */
    virtual void apply(const char* const data, const size_t length) noexcept;

    /**
     * Appends the sequence that updates the terminal to the contents of the back buffer to out_data,
     * and adopts the contents of the back buffer as the new contents of the front buffer
     *
     * @throws std::bad_alloc
     */
    virtual void render(std::vector<char>& out_data);

  private:
    // Color encoding: the default color of the terminal, an indexed color of the 256 color palette,
    // or a 24 bit RGB color
    static constexpr uint32_t COLOR_DEFAULT     = 0;
    static constexpr uint32_t COLOR_INDEXED     = 0x01000000;
    static constexpr uint32_t COLOR_RGB         = 0x02000000;
    static constexpr uint32_t COLOR_VALUE_MASK  = 0x00FFFFFF;

    static constexpr uint8_t FLAG_BOLD          = 0x01;
    static constexpr uint8_t FLAG_DIM           = 0x02;
    static constexpr uint8_t FLAG_UNDERLINE     = 0x04;
    static constexpr uint8_t FLAG_BLINK         = 0x08;
    static constexpr uint8_t FLAG_REVERSE       = 0x10;

    // Maximum length of the UTF-8 encoding of a single character
    static constexpr size_t MAX_CHAR_LENGTH     = 4;

    // Guards against unbounded growth of the CSI sequence buffer if the input is not a valid sequence
    static constexpr size_t MAX_CSI_LENGTH      = 64;

    struct Attributes
    {
        uint32_t    fg      {COLOR_DEFAULT};
        uint32_t    bg      {COLOR_DEFAULT};
        uint8_t     flags   {0};
    };

    struct Cell
    {
        // UTF-8 encoding of the character that the cell displays.
        // A text_length of zero marks the second cell of a double width character, which displays
        // the right half of the character that the preceding cell holds.
        char        text[MAX_CHAR_LENGTH]   {' ', '\0', '\0', '\0'};
        uint8_t     text_length             {1};
        uint32_t    fg                      {COLOR_DEFAULT};
        uint32_t    bg                      {COLOR_DEFAULT};
        uint8_t     flags                   {0};
    };

    enum class parser_state : uint8_t
    {
        TEXT,
        ESCAPE,
        CSI,
        OSC,
        OSC_ESCAPE
    };

    uint16_t cols;
    uint16_t rows;

    std::vector<Cell> back_buffer;
    std::vector<Cell> front_buffer;

    // If set, the next render() call updates every cell of the terminal
    bool full_update    {true};

    // State of the interpreter that is fed by apply()
    parser_state    state           {parser_state::TEXT};
    uint16_t        cursor_col      {0};
    uint16_t        cursor_row      {0};
    bool            cursor_visible  {true};
    Attributes      cur_attr;
    std::string     csi_seq;
    char            utf8_seq[MAX_CHAR_LENGTH]   {'\0', '\0', '\0', '\0'};
    uint8_t         utf8_length     {0};
    uint8_t         utf8_expected   {0};

    // State that the terminal was left in by the previous render() call
    Attributes      out_attr;
    uint16_t        out_cursor_col      {0};
    uint16_t        out_cursor_row      {0};
    bool            out_cursor_visible  {true};

    void clear_buffers() noexcept;
    void apply_byte(const char byte) noexcept;
    void apply_char(const char* const text, const uint8_t text_length) noexcept;
    void apply_csi(const char final_byte) noexcept;
    void apply_sgr(const std::vector<uint32_t>& params) noexcept;
    void erase_cells(const size_t start_index, const size_t end_index) noexcept;
    void parse_params(std::vector<uint32_t>& params, size_t& prefix_length) const;

    static bool equal_cells(const Cell& cell, const Cell& other) noexcept;

    // Number of columns that the terminal advances the cursor by when it displays the character.
    // Zero for combining characters, two for double width characters, otherwise one.
    static uint8_t char_width(const char* const text, const uint8_t text_length) noexcept;

    static void append_text(std::vector<char>& out_data, const char* const text);
    static void append_number(std::vector<char>& out_data, const uint32_t number);
    static void append_cursor_pos(std::vector<char>& out_data, const uint16_t col, const uint16_t row);
    static void append_color(std::vector<char>& out_data, const uint32_t color, const bool foreground);
    void append_attributes(std::vector<char>& out_data, const Cell& cell);
};

#endif /* SCREENBUFFER_H */
