#!/bin/sh
# FileOnOff Monitor script
# Expects Resource Name
#
# Copyright (C) 2017 LINBIT HA-Solutions GmbH
# Roland Kammerer <roland.kammerer@linbit.com>
###

. ${VCS_HOME}/bin/drbd_inc.sh
RESNAME=$1

ST=$( ${DRBDADM} role "${RESNAME}" )
ROLE=${ST%/*}
case $ROLE in
	Primary)
		exit 101 # online (101 as a start, inc confidence later)
		;;
	Secondary)
		exit 100 # offline
		;;
	*)
		exit 99 # unknown
		;;
esac
