global { disable-ip-verification; }
# This file was generated by drbdmanage(8), do not edit manually.
#dm-meta:{"create_date": "2017-09-02T12:32:53.114854"}

resource r0 {
   net {
       allow-two-primaries yes;
       shared-secret "EIUhGoz9e+FUY+XB/wX3";
       cram-hmac-alg sha1;
   }
   connection-mesh {
      hosts undertest pve3 pve2;
   }
    on undertest {
        node-id 1;
        address ipv4 10.1.1.1:7006;
        volume 0 {
            device minor 143;
            disk /dev/drbdpool/vm-105-disk-1_00;
            disk {
                size 4194304k;
            }
            meta-disk internal;
        }
    }
    on pve3 {
        node-id 2;
        address ipv4 10.1.1.3:7006;
        volume 0 {
            device minor 143;
            disk /dev/drbdpool/vm-105-disk-1_00;
            disk {
                size 4194304k;
            }
            meta-disk internal;
        }
    }
    on pve2 {
        node-id 0;
        address ipv4 10.1.1.2:7006;
        volume 0 {
            device minor 143;
            disk /dev/drbdpool/vm-105-disk-1_00;
            disk {
                size 4194304k;
            }
            meta-disk internal;
        }
    }
}
