#!/bin/sh

_mandir=/usr/share/man
case $1 in purge|remove|deconfigure)
    update-rc.d drbd remove >/dev/null
    # remove compat symlinks installed by .postinst
    rm -f /sbin/drbdsetup /sbin/drbdmeta /sbin/drbdadm

    for lang in / /ja/; do
	for man_ver in 9.0 8.4 8.3 ; do
	    master_link=${_mandir}${lang}man8/drbd-${man_ver}.8.gz 
	    link_group_name=drbd-man${lang#/}
	    link_group_name=${link_group_name%/}
	    update-alternatives --remove $link_group_name $master_link || true
	done
    done
    ;;
esac

#DEBHELPER#
