#!/bin/sh
# FileOnOff Monitor script
# Expects Resource Name
#
# Copyright (C) 2017 LINBIT HA-Solutions GmbH
# Roland Kammerer <roland.kammerer@linbit.com>
###

. ${VCS_HOME}/bin/drbd_inc.sh
RESNAME=$1; shift;
. $VCS_HOME/bin/ag_i18n_inc.sh

VCSAG_SET_ENVS $RESNAME

VCSAG_GET_ATTR_VALUE "ResName" -1 1 "$@"
DRBDRESNAME=${VCSAG_ATTR_VALUE}

ST=$( ${DRBDADM} role "${DRBDRESNAME}" )
ROLE=${ST%/*}
case $ROLE in
	Primary)
		exit 101 # online (101 as a start, inc confidence later)
		;;
	Secondary)
		exit 100 # offline
		;;
	*)
		exit 99 # unknown
		;;
esac
