#!/bin/sh
# DRBDConfigure offline entry point
# Expects DRBD Resource Name in ResName attribute
#
# License: GPL-2.0
# Copyright (C) 2017 LINBIT HA-Solutions GmbH
# Roland Kammerer <roland.kammerer@linbit.com>
# Lars Ellenberg <lars.ellenberg@linbit.com>
###

LINBITvcsag_bin=/opt/LINBITvcsag/bin
drbd_inc=$LINBITvcsag_bin/drbd_inc.sh

. $drbd_inc || { >&2 echo "$0: Failed to source $drbd_inc"; exit 1; }

${DRBDADM} down "${DRBDRESNAME}" || exit $VCSAG_EP_FAILED
